# Project Information
site_name: CTF Wiki EN 
site_description: CTF Wiki EN 
site_author: mahaloz 
site_url: https://ctf-wiki.mahaloz.re 

# Repository
repo_name: 'ctf-wiki/ctf-wiki-en'
repo_url: 'https://github.com/mahaloz/ctf-wiki-en'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2021 mahaloz'

# Contents
nav:
    - Introduction:
        - Getting Started: index.md
        - CTF History: introduction/history.md
        - Introduction to CTF Competition Form: introduction/mode.md
        - CTF Contest Content: introduction/content.md
        - Offline Attack and Defense Experience Summary: introduction/experience.md
        - CGC Super Challenge: introduction/cgc.md
        - Learning Resources: introduction/resources.md

    - Misc:
        - Miscellaneous Introduction: misc/introduction.md
        - Information Gathering Technology: misc/recon.md
        - Code Analysis:
            - Commonly Used Coding in the Communication Field: misc/encode/communication.md
            - Computer Related Coding: misc/encode/computer.md
            - Commonly Used Encodings in the Real World: misc/encode/modern.md
        - Forensic Steganography: misc/prefix.md
        - Image Analysis:
            - Introduction to Image Analysis: misc/picture/introduction.md
            - PNG: misc/picture/png.md
            - JPG: misc/picture/jpg.md
            - GIF: misc/picture/gif.md
        - Traffic Packet Analysis:
            - Introduction to Traffic Packet Analysis: misc/traffic/introduction.md
            - PCAP File Repairing: misc/traffic/fix.md
            - Protocol Analysis:
                - Overview of Protocol Analysis: misc/traffic/protocols/README.md
                - Wireshark: misc/traffic/protocols/Wireshark.md
                - HTTP: misc/traffic/protocols/HTTP.md
                - HTTPS: misc/traffic/protocols/HTTPS.md
                - FTP: misc/traffic/protocols/FTP.md
                - DNS: misc/traffic/protocols/DNS.md
                - WIFI: misc/traffic/protocols/WIFI.md
                - USB: misc/traffic/protocols/USB.md
            - Data Extraction: misc/traffic/data.md
        - Compressed Package Analysis:
            - ZIP Format: misc/archive/zip.md
            - RAR Format: misc/archive/rar.md
        - Audio Steganography: misc/audio/introduction.md
        - Disk Memory Analysis:
            - Introduction: misc/disk-memory/introduction.md
            - Title: misc/disk-memory/problem.md
        - Other:
            - pyc File: misc/other/pyc.md
    - Crypto:
        - Introduction to Cryptography: crypto/introduction.md
        - Basic Mathematics:
            - Introduction: crypto/basic/introduction.md
        - Classical Cryptography:
            - Introduction to Classical Cryptography: crypto/classical/introduction.md
            - Single table Substitution Cipher: crypto/classical/monoalphabetic.md
            - Multi-table Substitution Cipher: crypto/classical/polyalphabetic.md
            - Other Types of Cipher: crypto/classical/others.md
            - Summary: crypto/classical/summary.md
        - Stream Cipher:
            - Introduction: crypto/streamcipher/intro.md
            - Pseudo Random Number Generator:
                - Introduction: crypto/streamcipher/prng/intro.md
                - Cryptographic Security Pseudo-random Number Generator: crypto/streamcipher/prng/csprng.md
                - Challenge Examples: crypto/streamcipher/prng/problem.md
            - Linear Congruence Generator:
                - Introduction: crypto/streamcipher/lcg/intro.md
                - Example: crypto/streamcipher/lcg/challenge.md
            - Feedback Shift Register:
                - Introduction: crypto/streamcipher/fsr/intro.md
                - Linear Feedback Shift Register: crypto/streamcipher/fsr/lfsr.md
                - Nonlinear Feedback Shift Register: crypto/streamcipher/fsr/nfsr.md
            - Special Stream Cipher:
                - RC4: crypto/streamcipher/special/rc4.md
        - Block Cipher:
            - Introduction to Block Cipher: crypto/blockcipher/introduction.md
            - ARX: crypto/blockcipher/arx-operations.md
            - DES: crypto/blockcipher/des.md
            - IDEA: crypto/blockcipher/idea.md
            - AES: crypto/blockcipher/aes.md
            - Simon and Speck: crypto/blockcipher/simon-speck.md
            - Group Mode:
                - Introduction: crypto/blockcipher/mode/introduction.md
                - Padding Methods: crypto/blockcipher/mode/padding.md
                - ECB: crypto/blockcipher/mode/ecb.md
                - CBC: crypto/blockcipher/mode/cbc.md
                - PCBC: crypto/blockcipher/mode/pcbc.md
                - CFB: crypto/blockcipher/mode/cfb.md
                - OFB: crypto/blockcipher/mode/ofb.md
                - CTR: crypto/blockcipher/mode/ctr.md
                - Padding Oracle Attack: crypto/blockcipher/mode/padding-oracle-attack.md
        - Asymmetric Cryptography:
            - Introduction to Asymmetric Cryptography: crypto/asymmetric/introduction.md
            - RSA:
                - RSA Introduction: crypto/asymmetric/rsa/rsa_theory.md
                - Modulo-related Attacks: crypto/asymmetric/rsa/rsa_module_attack.md
                - Public Key Index Related Attacks: crypto/asymmetric/rsa/rsa_e_attack.md
                - Private Key d Related Attacks: crypto/asymmetric/rsa/rsa_d_attack.md
                - Coppersmith Related Attacks: crypto/asymmetric/rsa/rsa_coppersmith_attack.md
                - Chosen Plain Cipher Attack: crypto/asymmetric/rsa/rsa_chosen_plain_cipher.md
                - Side Channel Attack: crypto/asymmetric/rsa/rsa_side_channel.md
                - Bleichenbacher Attack: crypto/asymmetric/rsa/rsa_pkcs_attack.md
                - Challenge Examples: crypto/asymmetric/rsa/rsa_complex.md
            - Knapsack Cipher: crypto/asymmetric/knapsack/knapsack.md
            - Discrete Log Correlation:
                - Discrete Logarithm: crypto/asymmetric/discrete-log/discrete-log.md
                - Elgamal: crypto/asymmetric/discrete-log/elgamal.md
                - ECC: crypto/asymmetric/discrete-log/ecc.md
            - Lattice-based Cryptography:
                - Lattice Overview: crypto/asymmetric/lattice/overview.md
                - Introduction to Lattices: crypto/asymmetric/lattice/introduction.md
                - Lattice-based Algorithm: crypto/asymmetric/lattice/lattice-reduction.md
                - CVP: crypto/asymmetric/lattice/cvp.md
        - Hash Function:
            - Introduction to the Hash Function: crypto/hash/introduction.md
            - MD5: crypto/hash/md5.md
            - SHA1: crypto/hash/sha1.md
            - FNV: crypto/hash/fnv.md
            - Hash Attack: crypto/hash/attack.md
            - Challenge Examples: crypto/hash/complex.md
        - Digital Signature:
            - Introduction to Digital Signatures: crypto/signature/introduction.md
            - RSA Digital Signature: crypto/signature/rsa.md
            - ElGamal Digital Signature: crypto/signature/elgamal.md
            - DSA Digital Signature: crypto/signature/dsa.md
        - Summary of Attack Techniques:
            - Introduction: crypto/attack-summary/attack-mode.md
            - Intermediate Encounter Attack: crypto/attack-summary/meet-in-the-middle.md
            - Bit attack: crypto/attack-summary/bit-attack.md
        - Certificate Format: crypto/certificate/introduction.md
    - Web:
        - Introduction to Web Applications: web/introduction.md
        - SQL Injection: web/sqli.md
        - XSS Cross-site Scripting Attack: web/xss.md
        - CSRF Cross-site Request Forgery: web/csrf.md
        - SSRF Server Request Forgery: web/ssrf.md
        - PHP Code Auditing: web/php/php.md
    - Assembly:
        - x86_x64: assembly/x86-x64/readme.md
        - mips: assembly/mips/readme.md
        - arm: assembly/arm/readme.md
    - Executable:
        - ELF file:
            - ELF File Basic Structure: executable/elf/elf-structure.md
            - Program Loading: executable/elf/program-loading.md
            - Program Link: executable/elf/program-linking.md
            - Program Execution Flow: executable/elf/running-overview.md
        - PE file:
            - PE File Basic Structure: executable/pe/pe-excutable.md
            - PE Import Table: executable/pe/pe-import-table.md
            - PE Export Table: executable/pe/pe-export-table.md
            - PE Relocation Table: executable/pe/pe-relocation-table.md
    - Reverse Engineering:
        - Reverse Overview:
            - Software Reverse Engineering Introduction: reverse/introduction.md
            - Common Encryption Algorithms and Code Recognition: reverse/Identify-Encode-Encryption/introduction.md
            - Labyrinth Problem: reverse/maze/maze.md
            - Virtual Machine Command Analysis: reverse/vm/vm.md
            - Unicorn Engine Introduction: reverse/unicorn/introduction.md
        - Linux Reverse:
            - Linux Reverse Technology:
                - LD_PRELOAD: reverse/linux/ld_preload.md
                - Incorrect Disassembly Fix: reverse/linux/false-disasm.md
                - Detecting Breakpoints Bypassing: reverse/linux/detect-bp.md
                - Detecting Debugging Bypassing: reverse/linux/detect-dbg.md
        - Windows Reverse:
            - Shelling Technology:
                - Introduction to the Protective case: reverse/windows/unpack/packer-introduction.md
                - Single Step Tracking Method: reverse/windows/unpack/trace.md
                - ESP Law: reverse/windows/unpack/esp.md
                - One Step to the OEP Method: reverse/windows/unpack/direct-oep.md
                - Memory Mirroring Method: reverse/windows/unpack/memory.md
                - Last Exception Method: reverse/windows/unpack/last-exception.md
                - SFX Method: reverse/windows/unpack/sfx.md
                - DUMP and IAT Reconstruction: reverse/windows/unpack/fix-iat.md
                - Manually Find the IAT and Rebuild It Using ImportREC: reverse/windows/unpack/manually-fix-iat.md
                - DLL File Unpacking: reverse/windows/unpack/unpack-dll.md
            - Anti-debugging Technology:
                - NtGlobalFlag: reverse/windows/anti-debug/ntglobalflag.md
                - Heap Flags: reverse/windows/anti-debug/heap-flags.md
                - The Heap: reverse/windows/anti-debug/the-heap.md
                - Interrupt 3: reverse/windows/anti-debug/int-3.md
                - IsDebuggerPresent: reverse/windows/anti-debug/isdebuggerpresent.md
                - CheckRemoteDebuggerPresent: reverse/windows/anti-debug/checkremotedebuggerpresent.md
                - NtQueryInformationProcess: reverse/windows/anti-debug/ntqueryinformationprocess.md
                - ZwSetInformationThread: reverse/windows/anti-debug/zwsetinformationthread.md
                - Flower command: reverse/windows/anti-debug/junk-code.md
                - Anti-debug technical example: reverse/windows/anti-debug/example.md
    - Pwn:
        - Pwn Overview:
            - pwn/readme.md
        - Linux Pwn:
            - Security Protection Mechanism:
                - Canary: pwn/linux/mitigation/canary.md
            - Stack Overflow:
                - Stack Introduction: pwn/linux/stackoverflow/stack-intro.md
                - Stack Overflow Principle: pwn/linux/stackoverflow/stackoverflow-basic.md
                - Basic ROP: pwn/linux/stackoverflow/basic-rop.md
                - Intermediate ROP: pwn/linux/stackoverflow/medium-rop.md
                - Advanced ROP: pwn/linux/stackoverflow/advanced-rop.md
                - ROP Tricks: pwn/linux/stackoverflow/fancy-rop.md
            - Format String Vulnerability:
                - Format String Vulnerability Principle: pwn/linux/fmtstr/fmtstr_intro.md
                - Format String Exploit: pwn/linux/fmtstr/fmtstr_exploit.md
                - Format String Vulnerability Example: pwn/linux/fmtstr/fmtstr_example.md
                - Format String Vulnerability Detection: pwn/linux/fmtstr/fmtstr_detect.md
            - Glibc Heap Related:
                - Introduction to Heap: pwn/linux/glibc-heap/introduction.md
                - Heap Overview: pwn/linux/glibc-heap/heap_overview.md
                - Heap Related Data Structure: pwn/linux/glibc-heap/heap_structure.md
                - In-depth Understanding of Ptmalloc2:
                    - Implementation: pwn/linux/glibc-heap/implementation/overview.md
                    - Basic Functions in the heap implementation: pwn/linux/glibc-heap/implementation/basic.md
                    - Heap Initialization: pwn/linux/glibc-heap/implementation/heap-init.md
                    - Allocate Heap Memory: pwn/linux/glibc-heap/implementation/malloc.md
                    - Free Heap Memory: pwn/linux/glibc-heap/implementation/free.md
                    - Tcache: pwn/linux/glibc-heap/implementation/tcache.md
                    - malloc_state: pwn/linux/glibc-heap/implementation/malloc_state.md
                    - Other: pwn/linux/glibc-heap/implementation/misc.md
                - Heap Overflow: pwn/linux/glibc-heap/heapoverflow_basic.md
                - Heap-based Off-By-One: pwn/linux/glibc-heap/off_by_one.md
                - Chunk Extend/Overlapping: pwn/linux/glibc-heap/chunk_extend_overlapping.md
                - Unlink: pwn/linux/glibc-heap/unlink.md
                - Use After Free: pwn/linux/glibc-heap/use_after_free.md
                - Fastbin Attack: pwn/linux/glibc-heap/fastbin_attack.md
                - Unsorted Bin Attack: pwn/linux/glibc-heap/unsorted_bin_attack.md
                - Large Bin Attack: pwn/linux/glibc-heap/large_bin_attack.md
                - Tcache Attack: pwn/linux/glibc-heap/tcache_attack.md
                - House of Einherjar: pwn/linux/glibc-heap/house_of_einherjar.md
                - House of Force: pwn/linux/glibc-heap/house_of_force.md
                - House of Lore: pwn/linux/glibc-heap/house_of_lore.md
                - House of Orange: pwn/linux/glibc-heap/house_of_orange.md
                - House of Rabbit: pwn/linux/glibc-heap/house_of_rabbit.md
                - House of Roman: pwn/linux/glibc-heap/house_of_roman.md
            - IO_FILE Related:
                - FILE Structure Description: pwn/linux/io_file/introduction.md
                - Forged Vtable to Hijack Control Flow: pwn/linux/io_file/fake-vtable-exploit.md
                - FSOP: pwn/linux/io_file/fsop.md
                - Use of IO_FILE Under Glibc 2.24: pwn/linux/io_file/exploit-in-libc2.24.md
            - Race Condition:
                - Race Condition Introduction: pwn/linux/race-condition/introduction.md
                - Example: pwn/linux/race-condition/problem.md
            - Integer Overflow:
                - Introduction to The Principle of Integer Overflow: pwn/linux/integeroverflow/intof.md
            - Sandbox Escape:
                - Python Sandbox Escape: pwn/linux/sandbox/python-sandbox-escape.md
            - Linux Kernel:
                - Environment Setup: pwn/linux/kernel/environment.md
                - Basics: pwn/linux/kernel/basic_knowledge.md
                - Kernel-UAF: pwn/linux/kernel/kernel_uaf.md
                - Kernel-ROP: pwn/linux/kernel/kernel_rop.md
                - ret2usr: pwn/linux/kernel/ret2usr.md
                - bypass-smep: pwn/linux/kernel/bypass_smep.md
                - Double Fetch: pwn/linux/kernel/double-fetch.md
            - arm-pwn:
                - Environment Setup: pwn/linux/arm/environment.md
                - arm-rop: pwn/linux/arm/arm_rop.md
            - Summary:
                - Address Leaking: pwn/linux/summary/get-address.md
                - Hijack Control Flow: pwn/linux/summary/hijack-control-flow.md
                - Get Shell: pwn/linux/summary/get-shell.md

        - Windows Pwn:
            - Overview: pwn/windows/readme.md
            - Stack Overflow:
                - Stack Introduction: pwn/windows/stackoverflow/stack-introduce.md
                - Stack Overflow Principle: pwn/windows/stackoverflow/stackoverflow-basic.md
                - shellcode-in-stack: pwn/windows/stackoverflow/shellcode-in-stack.md

    - Android:
        - Android Development Basics: android/basic_develop/basic_develop.md
        - Android Application Operating Mechanism Brief:
            - Basics: android/basic_operating_mechanism/readme.md
            - The Operating Mechanism of the Java Layer in Android:
                - Andriod Native: android/basic_operating_mechanism/java_layer/readme.md
                - Smali Introduction: android/basic_operating_mechanism/java_layer/smali/smali.md
                - Dex and ODEX:
                    - DEX: android/basic_operating_mechanism/java_layer/dex/dex.md
                    - ODEX: android/basic_operating_mechanism/java_layer/dex/odex.md
            - Android Native Layer Introduction:
                - Android SO: android/basic_operating_mechanism/native_layer/so.md

            - Android Reverse Basic Introduction:
                - Brief Description: android/basic_reverse/overview.md
                - Android Key Part Location: android/basic_reverse/android_code_location.md
                - Android Simple Static Analysis:
                    - Android Java Layer Static Analysis: android/basic_reverse/static/java-example.md
                    - Android Native Layer Static Analysis: android/basic_reverse/static/so-example.md
                    - Android Static Analysis Hybrid Example: android/basic_reverse/static/complex-example.md
                - Android Simple Dynamic Analysis:
                    - Dynamic Debugging: android/basic_reverse/dynamic/dynamic_debug.md
                    - Android Dynamic Debugging SO: android/basic_reverse/dynamic/ida_native_debug.md
    - ICS:
        - ICS_CTF Contest: ics/ctfs.md
        - ICS_CTF found: ics/discover.md
        - ICS_CTF uses: ics/exploit.md
        - ICS_CTF Learning Resources: ics/learn.md


# Theme
theme:
  name: 'material'
  language: 'en'
  palette:
    scheme: 'slate'
    primary: 'pink'
    accent: 'purple'
  icon:
    logo: 'material/school'
  features:
    - tabs
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'ctf-wiki'
  copyright: 'CC BY-NC-SA 4.0'

extra_javascript:
    - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
    - '_static/js/extra.js'
    - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
    - '_static/css/extra.css'

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - meta
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
